/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\sci_fi_monitor.glb --transform 
Files: .\sci_fi_monitor.glb [448.16KB] > D:\UpWork\Portfolio\Nextjs-Creative-Portfolio-Starter-Code-Files\public\models\sci_fi_monitor-transformed.glb [136.09KB] (70%)
Author: carlin.chu (https://sketchfab.com/carlin.chu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-monitor-cc2f49493806480e95faeef4042f206c
Title: sci fi monitor🖥️
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/sci_fi_monitor-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Cube" scale={0.01}>
          <group name="pCube18" position={[0, -1, 0]} scale={[1, 0.274, 1]}>
            <mesh name="pCube18_TV_MTL_0" geometry={nodes.pCube18_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube17" position={[0, -1, 0]} scale={[1, 0.274, 1]}>
            <mesh name="pCube17_TV_MTL_0" geometry={nodes.pCube17_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube16" position={[0, -1, 0]} scale={[1, 0.274, 1]}>
            <mesh name="pCube16_TV_MTL_0" geometry={nodes.pCube16_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube15" position={[0, -1, 0]}>
            <mesh name="pCube15_TV_MTL_0" geometry={nodes.pCube15_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube14" position={[0, -1, 0]}>
            <mesh name="pCube14_TV_MTL_0" geometry={nodes.pCube14_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube13" position={[0, -1, 0]}>
            <mesh name="pCube13_TV_MTL_0" geometry={nodes.pCube13_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube12" position={[0, -1, 0]}>
            <mesh name="pCube12_TV_MTL_0" geometry={nodes.pCube12_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
        </group>
        <group name="cone" position={[0, 0.12, 0]} rotation={[0, 0, Math.PI]} scale={0.01}>
          <group name="pCube9" position={[-9, -0.53, 0]} scale={0}>
            <mesh name="pCube9_TV_MTL_0" geometry={nodes.pCube9_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube10" position={[-8.381, -0.53, 0]} scale={0}>
            <mesh name="pCube10_TV_MTL_0" geometry={nodes.pCube10_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube11" position={[-7.742, -0.53, 0]} scale={0}>
            <mesh name="pCube11_TV_MTL_0" geometry={nodes.pCube11_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
        </group>
        <group name="cone_1" scale={0.01}>
          <group name="pCube9_1" position={[-9, -0.53, 0]} scale={0}>
            <mesh name="pCube9_TV_MTL_0_1" geometry={nodes.pCube9_TV_MTL_0_1.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube10_1" position={[-8.381, -0.53, 0]} scale={0}>
            <mesh name="pCube10_TV_MTL_0_1" geometry={nodes.pCube10_TV_MTL_0_1.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube11_1" position={[-7.742, -0.53, 0]} scale={0}>
            <mesh name="pCube11_TV_MTL_0_1" geometry={nodes.pCube11_TV_MTL_0_1.geometry} material={materials.TV_MTL} />
          </group>
        </group>
        <mesh name="BG_BG_MTL_0" geometry={nodes.BG_BG_MTL_0.geometry} material={materials.BG_MTL} position={[0, -0.025, 0.015]} scale={0.015} />
        <mesh name="pPlane1_monter_MTL_0" geometry={nodes.pPlane1_monter_MTL_0.geometry} material={materials.monter_MTL} position={[0, 0.06, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.157, 0.01, 0.087]} />
        <mesh name="pCube3_TV_MTL_0" geometry={nodes.pCube3_TV_MTL_0.geometry} material={materials.TV_MTL} position={[0, 0.05, 0]} rotation={[0, 0, Math.PI]} scale={[0.16, 0.09, 0.002]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sci_fi_monitor-transformed.glb')
