/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [5.03KB] > D:\UpWork\Portfolio\Nextjs-Creative-Portfolio-Starter-Code-Files\public\models\diploma_frame\scene-transformed.glb [239.93KB] (-4670%)
Author: DrewA (https://sketchfab.com/DrewA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diploma-frame-9030281e7df84ca8b544c2acaa3688a0
Title: Diploma Frame
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} rotation={[1.329, 0, 0]} scale={[0.007, 0.001, 0.008]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
