/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [22.09KB] > D:\UpWork\Portfolio\Nextjs-Creative-Portfolio-Starter-Code-Files\public\models\computer\scene-transformed.glb [852.34KB] (-3758%)
Author: Cybertron B-127 (https://sketchfab.com/robo-reboot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-5fd9d1edda1942eda0bb60329a499cc7
Title: Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material} position={[-0.308, 0.27, 0.05]} scale={[0.455, 0.303, 0.001]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} position={[-0.11, 0.064, 0.213]} scale={[0.507, 0.318, 0.001]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_2} position={[0.18, 0.309, 0.064]} scale={[0.415, 0.233, 0.001]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} position={[0.576, -0.032, 0.289]} scale={[0.31, 0.175, 0.001]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_4} position={[0.449, 0.061, 0.125]} scale={[0.353, 0.235, 0.001]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.material_5} position={[0.349, 0.202, 0.114]} scale={[0.354, 0.199, 0.001]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_6} position={[-0.362, -0.167, 0.229]} scale={[0.463, 0.26, 0.001]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_7} position={[0.067, -0.17, 0.239]} scale={[0.332, 0.287, 0.001]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.material_8} position={[0.476, -0.199, 0.05]} scale={[0.418, 0.235, 0.001]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
